version: '3'
services:
  main:
    image: kupa2004:latest
    build: ./build
    volumes:
      - /tmp:/tmp:Z
  web:
    build: ./run
    ports:
      - 8083:8080
    depends_on:
      - main
    volumes:
      - /tmp:/tmp
