version: '3'
services:
  main:
    image: kupa2004:latest
    build: ./build
    volumes:
      - ./home/boxfuse-sample-java-war-hello/target:/home/run
  web:
    build: tomcat:latest
    ports:
      - 8083:8080
    depends_on:
      - main
    volumes:
      - ./usr/local/tomcat/webapps:/home/run
