version: '3'
services:
  main:
    image: kupa2004:latest
    build: ./build
    volumes:
      - Temp:/tmp:Z
  web:
    build: ./run
    ports:
      - 8085:8080
    depends_on:
      - main
    volumes:
      - Temp:/tmp
volumes:
  Temp:
    external: true